fred_fx_series = {
    "euro_area": "DEXUSEU",
    "japan": "DEXJPUS",
    "china": "DEXCHUS",
    "canada": "DEXCAUS",
    "united_kingdom": "DEXUSUK",
    "south_korea": "DEXKOUS",
    "mexico": "DEXMXUS",
    "india": "DEXINUS",
    "brazil": "DEXBZUS",
    "australia": "DEXUSAL",
    "switzerland": "DEXSZUS",
    "sweden": "DEXSDUS",
    "norway": "DEXNOUS",
    "denmark": "DEXDNUS",
    "hong_kong": "DEXHKUS",
    "singapore": "DEXSIUS",
    "south_africa": "DEXSFUS",
    "taiwan": "DEXTAUS",
    "thailand": "DEXTHUS",
    "new_zealand": "DEXUSNZ",
    "malaysia": "DEXMAUS",
    "venezuela": "DEXVZUS"
}